<?php
$temp_html_head='';
$height=$value['orgminheight'];
$height=strlen($height)>0?$height.'px':'150px';
$srcName=$value['name'];
$is_data_form=$form['is_data_form'];

if(empty($_GET['plaintreeinit'])){
	
	$_GET['plaintreeinit']=true;
	$temp_html_head='<script>'
	.'function regular_str(str,name,rep){'
		.'var re=eval(\'/(name="\'+name+\'".*?listtext="[^"]*")/\');'
		.'var arr=re.exec(str);'
		.'var str2=arr[0];'
		.'str2=str2.replace(eval(\'/name="\'+name+\'".*?listtext="/\'),"");'
		.'str2=str2.replace(/"/,"");'
		.'str2=arr[0].replace(str2,rep);'
		.'str=str.replace(arr[0],str2);'
		.'return str;'
	.'}'
	.'function gethrefpar(name){'
	   .'var url=window.location.href+"";'
	   .'var i=0;'
	   .'if(url.indexOf("?")!= -1){'
		  .'var str=url.substr(url.indexOf("?")+1);'
		  .'strs=str.split("&");'
		  .'for(i=0;i<strs.length;i++){'
			  .'if(strs[i].split("=")[0]==name){'
				.'return unescape(strs[i].split("=")[1]);'
			  .'}'
		  .'}'
	   .'}'
	   .'return null;'
	.'}'
	.'function copypra(src,desc){'
		.'var i=0;'
		.'if(src==null){'
			.'desc+=\'null\';'
			.'return desc;'
		.'}'
		.'desc+=\'[\';var nexti=0;'
		.'for(i=0;i<src.length;i++){'
			.'var inx=0,ischildren=false;'
			.'for(xx in src[i]){'
				.'if(xx=="children"){'
					.'ischildren=true;'
					.'if(inx==0){'
						.'if(nexti>0)desc+=\',\';'
						.'desc+=\'{\';'
					.'}'
					.'if(inx>0)desc+=\',\';'
					.'desc+=\'"children":\';'
					.'var redesc=copypra(src[i][xx],\'\');'
					.'if(redesc==\'[]\')redesc=\'null\';'
					.'desc+=redesc;'
					.'inx++;'
				.'}else if(xx=="text" || xx=="url"){'
					.'if(inx==0){'
						.'if(nexti>0)desc+=\',\';'
						.'desc+=\'{\';'
					.'}'
					.'if(inx>0)desc+=\',\';'
					.'desc+=\'"\'+xx+\'":"\'+src[i][xx]+\'"\';'
					.'inx++;'
				.'}'
			.'}'
			.'if(inx>0){'
				.'if(ischildren==false){'
					.'if(inx>0)desc+=\',\';'
					.'desc+=\'"children":null\';'
				.'}'
				.'desc+="}";'
				.'nexti++;'
			.'}'
		.'}'
		.'desc+=\']\';'
		.'return desc;'
	.'}'
	.'function appendNode(inx,title,type){'
		.'var selnode=fuviewtrees[inx].getSelected();'
		.'$("#inputtextid").val("");'
		.'$("#inputlinkid").val(\'/s/listform.php?fieldtype=key&key=\');'
		.'if(type=="edit"){'
			.'if(selnode==null){'
				.'$.ligerDialog.error("请选择树节点");'
				.'return;'
			.'}'
			.'$("#inputtextid").val(selnode.data.text.replace(/amp;/ig,""));'
			.'$("#inputlinkid").val(selnode.data.url.replace(/amp;/ig,""));'
		.'}'
		.'m=$.ligerDialog.open({'
		.'target:$("#parid"),'
		.'title:title,'
		.'buttons:[{'
			.'text:"确定",onclick:function(){'
				.'m.hide();'
				.'var txt=$("#inputtextid").val();'
				.'if(txt==""){'
					.'$.ligerDialog.error("请输入节点文本");'
					.'return;'
				.'}'
				.'var lnk=$("#inputlinkid").val();'
				.'if(lnk==""){'
					.'$.ligerDialog.error("请输入连接地址");'
					.'return;'
				.'}'
				.'var nodes = [];'
				.'nodes.push({text:txt,url:lnk});'
				.'if(type=="edit"){'
					.'selnode.data.text=txt;'
					.'selnode.data.url=lnk;'
					.'fuviewtrees[inx].update(selnode.target,nodes);'
					.'$(selnode.target).find("span").html(txt);'
				.'}else{'
					.'if(selnode){'
						.'fuviewtrees[inx].append(selnode.target,nodes);'
					.'}else{'
						.'fuviewtrees[inx].append(null,nodes);'
					.'}'
				.'}'
				
			.'}'
		.'},{text:"取消",onclick:function(){m.hide();}}]});'
	.'}'
	.'function fuviewtreesitemdelete(obj,id){'
		.'if(obj==null)return;'
		.'var i=0;'
		.'for(i=0;i<obj.length;i++){'
			.'if(obj[i]!=null){'
				.'if(typeof(obj[i])=="object"){'
					.'if(typeof(obj[i].treedataindex)!="undefined"){'
						.'if(obj[i].treedataindex==id){'
							.'obj.splice(i,1);'
							.'break;'
						.'}'
					.'}'
					.'if(typeof(obj[i].children)!="undefined"){'
						.'fuviewtreesitemdelete(obj[i].children,id);'
					.'}'
				.'}'
			.'}'
		.'}'
	.'}'
	.'function plaintree_click($this){'
		.'var inx=$($this).parent().attr("inx");'
		.'var srcName=$($this).parent().attr("name");'
		.'var tp=$($this).html();'
		.'if(tp=="添加"){'
			.'appendNode(inx,"添加节点");'
		.'}else if(tp=="修改"){'
			.'appendNode(inx,"修改节点","edit");'
		.'}else if(tp=="删除"){'
			.'var node=fuviewtrees[inx].getSelected();'
			.'if(node){'
				.'fuviewtreesitemdelete(fuviewtrees[inx].data,node.data.treedataindex);'
				.'fuviewtrees[inx].remove(node.target);'
			.'}else{'
				.'$.ligerDialog.error("请选择树节点");'
			.'}'
		.'}else if(tp=="保存"){'
			.'var obj=fuviewtrees[inx].getData();'
			.'var json=copypra(obj,"");'
			.'var form_id="'.$_REQUEST['formid'].'";'
			.'if(form_id==""){'
				.'$.ligerDialog.error(\'保存失败：页面ID不正确\');'
				.'return;'
			.'}'
			.'var formtype="'.$form['is_data_form'].'";'
			.'if(formtype==""){'
				.'$.ligerDialog.error(\'保存失败：页面类别不正确\');'
				.'return;'
			.'}'
			.'var formeditor=regular_str($("#plaintreeid"+inx+"content").val(),srcName,encodeURI(json));'
			.'$.ajax({'
				.'type: \'POST\','
				.'url: \'/s/tp/wwwroot/index.php?s=/demo/formdesign/\','
				.'data: {form_id: form_id,\'design_content\':formeditor,\'formtype\':formtype},'
				.'dataType : \'json\','
				.'success: function(data) {'
					.'if(data.result==1){'
						.'$.ligerDialog.success(\'保存成功\');'
					.'}else{'
					 	.'$.ligerDialog.error(\'保存失败：\'+data.message);'
					.'}'
				.'},error: function(xhr, stat, e) { $.ligerDialog.error("保存失败：找不到地址！" ); }'
			.'});'
		.'}'
	.'}'
	.'$(function(){'
		.'window.fuviewtrees=Array();'
		.'var temp=\'<div id="parid" style="display:none;">\';'
		.'temp+=\'<p>文本：<input type="text" placeholder="请输入节点文本..." id="inputtextid"></p>\';'
		.'temp+=\'<p>地址：<input type="text" placeholder="请输入连接地址..." id="inputlinkid" value="/s/listform.php?fieldtype=key&key="></p>\';'
		.'temp+=\'</div>\';'
		.'$(document.body).append(temp);'
	.'});'
	
	.'</script>';
}

$temp_html=$temp_html_head;
$temp_html.='<div id="divbox" style="width:100%;height:'.$height.';overflow:hidden;background:#ff00000;">';

$temp_html.='<textarea id="plaintreeid'.$key.'content" style="display:none;">'.$form['content'].'</textarea>';
$temp_html.='<div id="menu" inx="'.$key.'" name="'.$srcName.'">';
$temp_html.=' <a href="javascript:;" onclick="plaintree_click(this);">添加</a>';
$temp_html.=' <a href="javascript:;" onclick="plaintree_click(this);">修改</a>';
$temp_html.=' <a href="javascript:;" onclick="plaintree_click(this);">删除</a>';
$temp_html.=' <a href="javascript:;" onclick="plaintree_click(this);">保存</a>';
$temp_html.='</div>';

$temp_html.='<div id="insidebox" style="width:100%;height:100%;overflow:hidden;">';
$temp_html.='<ul style="float:left;width:auto;height:auto;overflow:hidden;" id="plaintreeid'.$key.'ul"></ul>';
$temp_html.='<div id="right" style="width:80%;height:82%;float:right;">';
$temp_html.='<iframe src="" style="width:100%;height:100%;border:0;" id="plaintreeid'.$key.'iframe"></iframe>';
$temp_html.='</div></div></div>';
$temp_html.='<script>';
$temp_html.='$(function(){';
$temp_html.='fuviewtrees['.$key.']=$("#plaintreeid'.$key.'ul").ligerTree({checkbox: false,
		data:JSON.parse(decodeURI("'.$value['listtext'].'")),
		onSelect:function(node){
			if(node.data.children==null)
				$("#plaintreeid'.$key.'iframe").attr("src",""+node.data.url);
		}
	});';
$temp_html.='});';
$temp_html.='</script>';

?>

